name: networklogger_example
description: Example app for the networklogger package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  network_log_viewer:
    path: ../
  dio: ^5.7.0
  graphql: ^5.2.0

dev_dependencies:
  flutter_lints: ^6.0.0
